### ISSUE TITLE
Quest giver can have speech triggered numerous times

### ISSUE THREAD

**Issue by larouxn** [robwhitaker/godot-wild-jam-33#27]
If one presses E several times next to the quest giver, they will start their speech over and over again.

https://user-images.githubusercontent.com/1557529/120124791-f44e0e00-c1f0-11eb-8c91-46253d209f72.mp4

**Comment by robwhitaker** [comment]
Yeah, we could easily set a variable on the quest giver so they don't repeat themselves. It will also have to be persistent, of course (in case you walk off the map and come back).

**Comment by larouxn** [comment]
I think a variable would handle it well. I'm not concerned about walking elsewhere and returning unless we want to alter the content should the player return and interact again.

**Comment by larouxn** [comment]
Won't fix. 😅
